-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
--
-- Returns every example as a list of
-- `{ name = ..., filename = ..., source = ... }`, ordered as declared.
--
-- Each source is a Lua long-bracket string: no escape processing, so Rak
-- regexes and backslashes are stored exactly as written.

local examples = {}

examples[#examples + 1] = require("src/examples/hello")
examples[#examples + 1] = require("src/examples/quick")
examples[#examples + 1] = require("src/examples/osint_scan")
examples[#examples + 1] = require("src/examples/echo_server")
examples[#examples + 1] = require("src/examples/echo_client")
examples[#examples + 1] = require("src/examples/bench")
examples[#examples + 1] = require("src/examples/sql_client")
examples[#examples + 1] = require("src/examples/self_host")
examples[#examples + 1] = require("src/examples/sql_server")
examples[#examples + 1] = require("src/examples/pipeline")
examples[#examples + 1] = require("src/examples/regex")
examples[#examples + 1] = require("src/examples/binary_patterns")
examples[#examples + 1] = require("src/examples/traits")
examples[#examples + 1] = require("src/examples/ffi")
examples[#examples + 1] = require("src/examples/mmap")
examples[#examples + 1] = require("src/examples/async")
examples[#examples + 1] = require("src/examples/net_raw")
examples[#examples + 1] = require("src/examples/parsers")
examples[#examples + 1] = require("src/examples/macros")
examples[#examples + 1] = require("src/examples/import_demo")
examples[#examples + 1] = require("src/examples/VPN_keyexchange")
examples[#examples + 1] = require("src/examples/VPN_chacha_tunnel")
examples[#examples + 1] = require("src/examples/VPN_psk_tunnel")
examples[#examples + 1] = require("src/examples/VPN_vpn_over_http")
examples[#examples + 1] = require("src/examples/batteries")
examples[#examples + 1] = require("src/examples/osint")
examples[#examples + 1] = require("src/examples/core_v072")

return examples
