-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- async.rak: async
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[async]]

example.filename = [[async.rak]]

example.source = [[
// Async event loop: async fn, await, and futures.
async fn probe(host, port) {
    let open = await tcp_probe(host, port, 200)
    return open
}
dump await probe("127.0.0.1", 80)
dump await probe("127.0.0.1", 9999)
let f = tcp_probe("127.0.0.1", 22, 200)
dump fmt("port 22 open = {}", await f)
]]

return example
