-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- batteries.rak: batteries
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[batteries]]

example.filename = [[batteries.rak]]

example.source = [[
dump time_now()                       // seconds since the Unix epoch
dump date_today()                     // 2026-09-27
dump time_fmt(time_now(), "%Y/%m/%d") // strftime-style formatting

rand_seed(42)
dump rand_int(1, 100)
dump rand_hex(16)
let picked = rand_choice([80, 443, 8080])?
dump picked in [80, 443, 8080]        // true

let rows = csv_parse("name,port\nhttp,80\nhttps,443\n")
dump rows[1].name                      // https
dump csv_stringify([{ a: 1, b: 2 }, { a: 3, b: 4 }])

let cfg = yaml_parse("host: 127.0.0.1\nports: [80, 443]\n")?
dump cfg.host

let blob = gzip_compress(b"compress me")
dump gzip_decompress(blob)             // b"compress me"
]]

return example
