-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- binary_patterns.rak: binary_patterns
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[binary_patterns]]

example.filename = [[binary_patterns.rak]]

example.source = [[
// binary_patterns.rak -- binary pattern matching over byte slices.

fn sniff(data: bytes) {
    match data {
        [0x89, 'P', 'N', 'G', ..] => { return "png" },
        [0xFF, 0xD8, 0xFF, ..] => { return "jpeg" },
        ['%', 'P', 'D', 'F', ..] => { return "pdf" },
        _ => { return "unknown" },
    }
}

dump sniff(b"\x89PNG\x0d\x0a\x1a\x0a")  // png
dump sniff(b"\xFF\xD8\xFF\xE0")          // jpeg
dump sniff(b"%PDF-1.4")                      // pdf
]]

return example
