-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- core_v072.rak: core_v072
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[core_v072]]

example.filename = [[core_v072.rak]]

example.source = [[
// Language core (v0.7.2): `in`, destructuring let, slices.
dump "ell" in "hello"                  // true  (substring)
dump 443 in [80, 443, 8080]            // true  (array membership)
dump "port" in { port: 443 }           // true  (map key)
dump 0x4D in b"MZ"                     // true  (byte membership)

let (host, port) = ("example.com", 443)
dump host + ":" + port                 // example.com:443

let [first, second, rest] = [10, 20, 30]
dump first + rest                      // 40

struct Point { x: int, y: int }
let Point { x, y } = Point { x: 3, y: 4 }
dump x * y                             // 12

let d = [10, 20, 30, 40, 50]
dump d[1..3]                           // [20, 30]
dump d[..2]                            // [10, 20]
dump d[-2..]                           // [40, 50]
dump d[-1]                             // 50
dump "hello"[1..3]                     // el
]]

return example
