-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- echo_client.rak: echo_client
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[echo_client]]

example.filename = [[echo_client.rak]]

example.source = [[
let client = net_listen("127.0.0.1:0")
let _ = client

let s = net_connect("127.0.0.1:18392")
tcp_write(s, "hello rak server
")
let reply = tcp_read_line(s)
dump f"reply: {reply}"
tcp_close(s)
]]

return example
