-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- ffi.rak: ffi
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[ffi]]

example.filename = [[ffi.rak]]

example.source = [[
// FFI: call native C functions and manage raw memory.
extern "C" {
    fn abs(n: i32) -> i32
}
dump abs(-42)            // 42
let buf = ffi_alloc(4)
ffi_write(buf, 0, 0x41)
dump ffi_cstr_to_string(buf)  // "A"
ffi_free(buf)
let p = ffi_ptr(0xDEADBEEF)
dump fmt("ptr = 0x{:08X}", p)
]]

return example
