-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- hello.rak: hello
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[hello]]

example.filename = [[hello.rak]]

example.source = [[
dump "Hello, World"
]]

return example
