-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- import_demo.rak: import_demo
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[import_demo]]

example.filename = [[import_demo.rak]]

example.source = [[
// Python-style imports & exports. NOTE: this script uses 'import mymod'
// which resolves a sibling mymod/ package — save it next to a mymod/ folder
// (with init.rak + sub.rak) to run. It still highlights correctly here.
import mymod
dump mymod.PI
dump mymod.add(2, 3)
import mymod as m
dump m.add(1, 1)
from mymod import add
dump add(10, 20)
from mymod import add as plus, mul as times
dump plus(7, 8)
dump times(6, 7)
let PI = "local-pi"
from mymod import *
dump PI               // "local-pi" (local wins)
dump mul(3, 3)        // 9 (imported)
from mymod.sub import sub_add, SUB_NAME, add
dump SUB_NAME
dump sub_add(100, 1)
dump add(5, 6)
]]

return example
