-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- macros.rak: macros
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[macros]]

example.filename = [[macros.rak]]

example.source = [[
// Compile-time macros: AST-expanding templates with $param placeholders.
macro add1(x: expr) { $x + 1 }
dump add1!(41)          // 42
macro swap(a: expr, b: expr) {
    let t = $a
    t + $b
}
dump swap!(10, 20)      // 30
macro pair(a: expr, b: expr) { [$a, $b] }
dump pair!(1, 2)        // [1, 2]
const MAX_LEN = 256
dump MAX_LEN
]]

return example
