-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- mmap.rak: mmap
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[mmap]]

example.filename = [[mmap.rak]]

example.source = [[
// Memory-mapped files: inspect large files without loading them.
let m = mmap_open("examples/mmap_sample.bin", "r")
dump fmt("size = {} bytes", mmap_size(m))
let hdr = mmap_slice(m, 0, 8)
dump fmt("byte 0 = 0x{:02X}", hdr[0])
dump mmap_find(m, "GET")
let lines = mmap_lines_off(m, "\n")
dump fmt("line count = {}", len(lines))
]]

return example
