-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- net_raw.rak: net_raw
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[net_raw]]

example.filename = [[net_raw.rak]]

example.source = [[
// Raw sockets: forge IPv4/TCP/UDP packets with checksums.
let pkt = net_raw_tcp_syn("10.0.0.5", "10.0.0.10", 12345, 80)
dump fmt("syn packet = {} bytes", len(pkt))
dump fmt("byte 0 = 0x{:02X} (IPv4)", pkt[0])
dump fmt("byte 9 = 0x{:02X} (proto TCP)", pkt[9])
dump fmt("byte 33 = 0x{:02X} (SYN flag)", pkt[33])
dump net_raw_send(pkt)   // Ok(...) on unix w/ CAP_NET_RAW, Err(...) otherwise
]]

return example
