-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- osint.rak: osint
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[osint]]

example.filename = [[osint.rak]]

example.source = [[
// OSINT pack (v0.7.2): WHOIS, certificate-transparency, YARA, reports.
// whois_lookup("example.com") and ct_subdomains("example.com") hit the
// network -- uncomment when you have connectivity.

let w = whois_parse("Domain Name: EXAMPLE.COM\nRegistrar: RESERVED-Internet Assigned Numbers Authority\nName Server: A.IANA-SERVERS.NET\n")
dump w["registrar"]                   // RESERVED-Internet Assigned Numbers Authority

let rule = "rule pe_mz { strings: $mz = { 4D 5A ?? 00 03 } condition: $mz at 0 }"
let data = b"MZ\x90\x00\x03\x00\x00\x00\x04\x00"
dump yara_scan(rule, data)[0].rule    // pe_mz

let markdown = report_markdown({
  title: "Recon: example.com",
  meta: { target: "example.com", tool: "rakc osint pack", confidence: "high" },
  sections: {
    "Headline": ["registrar: RESERVED-Internet Assigned Numbers Authority"],
    "YARA": ["pe_mz matched ($mz at 0)"],
  },
})
dump markdown                          // Markdown evidence report
]]

return example
