-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- parsers.rak: parsers
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[parsers]]

example.filename = [[parsers.rak]]

example.source = [[
// DNS / TLS / PCAP wire-format parsers.
let q = dns_build("example.com", "A")
dump fmt("dns query = {} bytes", len(q))
dump dns_query("example.com", "A")   // Ok({answers: [...], truncated}) or Err offline
dump pcap_open("capture.pcap")       // Ok(<pcap>) or Err (needs --features pcap)
]]

return example
