-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- pipeline.rak: pipeline
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[pipeline]]

example.filename = [[pipeline.rak]]

example.source = [[
// pipeline.rak -- the |> pipeline operator (interpreter + VM).
// x |> f        desugars to  f(x)
// x |> f(a, b)  desugars to  f(x, a, b)

fn inc(n) { return n + 1 }
fn dbl(n) { return n * 2 }
fn add(a, b) { return a + b }

dump 5 |> inc |> dbl          // 12
dump 3 |> add(10)             // 13
dump [1, 2, 3, 4] |> sum      // 10
]]

return example
