-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- quick.rak: quick
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[quick]]

example.filename = [[quick.rak]]

example.source = [[
dump "=== Hello ==="
dump md5("password")
dump hex_encode("ABC")
dump base64_encode("hello")
dump fmt("0x{:04X}", 0x0050)
]]

return example
