-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- regex.rak: regex
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[regex]]

example.filename = [[regex.rak]]

example.source = [[
// regex.rak -- regex literals and matching.
// Flags: i (case-insensitive), m (multi-line), s (dotall), x (extended), g (no-op).

let re = /\d+/g
dump re.is_match("abc123")            // true
dump re.find_all("a1 b22 c333")       // [1, 22, 333]
dump re.find("no digits here")        // nil

let ws = /\s+/g
dump ws.replace("a  b   c", "_")      // a_b_c

// Free-function form (also works on the VM):
dump regex_find_all(/[a-z]+/g, "a1bc2def")   // [a, bc, def]
]]

return example
