-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- sql_server.rak: sql_server
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[sql_server]]

example.filename = [[sql_server.rak]]

example.source = [[
fn is_digit(c) {
    return c == "0" || c == "1" || c == "2" || c == "3" || c == "4" || c == "5" || c == "6" || c == "7" || c == "8" || c == "9"
}

fn is_alpha(c) {
    let code = ord(c)
    return (code >= 65 && code <= 90) || (code >= 97 && code <= 122) || c == "_"
}

fn is_alnum(c) {
    return is_alpha(c) || is_digit(c)
}

fn sql_lex(src) {
    let toks = []
    let i = 0
    let n = len(src)
    let keywords = {select: 1, from: 1, where: 1, insert: 1, into: 1, values: 1, create: 1, table: 1, delete: 1, and: 1, or: 1, not: 1, null: 1, int: 1, text: 1, bool: 1, update: 1, set: 1, drop: 1}
    while i < n {
        let c = src[i]
        if c == " " || c == "
" || c == "	" || c == "" {
            i = i + 1
        } else if c == "-" && i + 1 < n && src[i + 1] == "-" {
            while i < n && src[i] != "
" {
                i = i + 1
            }
        } else if c == "'" {
            i = i + 1
            let buf = ""
            while i < n && src[i] != "'" {
                buf = buf + src[i]
                i = i + 1
            }
            i = i + 1
            toks = push(toks, {ty: "string", value: buf})
        } else if c == """ {
            i = i + 1
            let buf = ""
            while i < n && src[i] != """ {
                buf = buf + src[i]
                i = i + 1
            }
            i = i + 1
            toks = push(toks, {ty: "ident", value: buf})
        } else if is_digit(c) {
            let buf = ""
            while i < n && is_digit(src[i]) {
                buf = buf + src[i]
                i = i + 1
            }
            toks = push(toks, {ty: "number", value: buf})
        } else if is_alpha(c) {
            let buf = ""
            while i < n && (is_alnum(src[i]) || src[i] == "_") {
                buf = buf + src[i]
                i = i + 1
            }
            let low = lower(buf)
            let iskw = false
            for k in keys(keywords) {
                if k == low {
                    iskw = true
                }
            }
            if iskw {
                toks = push(toks, {ty: "kw", value: low})
            } else {
                toks = push(toks, {ty: "ident", value: buf})
            }
        } else if c == "(" || c == ")" || c == "," || c == ";" || c == "*" || c == "." {
            toks = push(toks, {ty: "punct", value: c})
            i = i + 1
        } else if c == "=" {
            toks = push(toks, {ty: "op", value: "="})
            i = i + 1
        } else if c == "<" {
            if i + 1 < n && src[i + 1] == "=" {
                toks = push(toks, {ty: "op", value: "<="})
                i = i + 2
            } else if i + 1 < n && src[i + 1] == ">" {
                toks = push(toks, {ty: "op", value: "<>"})
                i = i + 2
            } else {
                toks = push(toks, {ty: "op", value: "<"})
                i = i + 1
            }
        } else if c == ">" {
            if i + 1 < n && src[i + 1] == "=" {
                toks = push(toks, {ty: "op", value: ">="})
                i = i + 2
            } else {
                toks = push(toks, {ty: "op", value: ">"})
                i = i + 1
            }
        } else if c == "!" && i + 1 < n && src[i + 1] == "=" {
            toks = push(toks, {ty: "op", value: "!="})
            i = i + 2
        } else {
            i = i + 1
        }
    }
    return toks
}

fn tok_at(toks, i) {
    if i < len(toks) {
        return toks[i]
    }
    return {ty: "eof", value: ""}
}

fn is_kw(toks, i, val) {
    let t = tok_at(toks, i)
    return t.ty == "kw" && t.value == val
}

fn is_punct(toks, i, val) {
    let t = tok_at(toks, i)
    return t.ty == "punct" && t.value == val
}

fn is_op(toks, i, val) {
    let t = tok_at(toks, i)
    return t.ty == "op" && t.value == val
}

fn lit_value(t) {
    if t.ty == "number" {
        return {kind: "num", value: t.value}
    }
    if t.ty == "string" {
        return {kind: "str", value: t.value}
    }
    if t.value == "null" || t.value == "NULL" {
        return {kind: "null", value: ""}
    }
    return {kind: "str", value: t.value}
}

fn parse_cond(toks, i) {
    let t = tok_at(toks, i)
    let col = ""
    if t.ty == "ident" {
        col = t.value
        i = i + 1
    }
    let op_t = tok_at(toks, i)
    let op = op_t.value
    if op_t.ty != "op" {
        return {expr: {op: "true"}, pos: i}
    }
    i = i + 1
    let val_t = tok_at(toks, i)
    let val = lit_value(val_t)
    i = i + 1
    return {expr: {op: op, col: col, value: val}, pos: i}
}

fn parse_and(toks, i) {
    let left_res = parse_cond(toks, i)
    let left = left_res.expr
    i = left_res.pos
    while is_kw(toks, i, "and") {
        i = i + 1
        let right_res = parse_cond(toks, i)
        let right = right_res.expr
        i = right_res.pos
        left = {op: "and", left: left, right: right}
    }
    return {expr: left, pos: i}
}

fn parse_or(toks, i) {
    let left_res = parse_and(toks, i)
    let left = left_res.expr
    i = left_res.pos
    while is_kw(toks, i, "or") {
        i = i + 1
        let right_res = parse_and(toks, i)
        let right = right_res.expr
        i = right_res.pos
        left = {op: "or", left: left, right: right}
    }
    return {expr: left, pos: i}
}

fn parse_where(toks, i) {
    return parse_or(toks, i)
}

fn parse_select(toks) {
    let i = 1
    let cols = []
    if is_punct(toks, i, "*") {
        cols = push(cols, "*")
        i = i + 1
    } else {
        let cont = true
        while cont {
            let t = tok_at(toks, i)
            if t.ty == "ident" {
                cols = push(cols, t.value)
                i = i + 1
                if is_punct(toks, i, ",") {
                    i = i + 1
                } else {
                    cont = false
                }
            } else {
                cont = false
            }
        }
    }
    let from = ""
    if is_kw(toks, i, "from") {
        i = i + 1
        let t = tok_at(toks, i)
        if t.ty == "ident" {
            from = t.value
            i = i + 1
        }
    }
    let where = nil
    if is_kw(toks, i, "where") {
        i = i + 1
        let res = parse_where(toks, i)
        where = res.expr
        i = res.pos
    }
    return {ty: "select", columns: cols, from: from, where: where}
}

fn parse_insert(toks) {
    let i = 1
    if !is_kw(toks, i, "into") {
        return {ty: "error", message: "expected INTO"}
    }
    i = i + 1
    let table = tok_at(toks, i).value
    i = i + 1
    let cols = []
    if is_punct(toks, i, "(") {
        i = i + 1
        let cont = true
        while cont {
            let t = tok_at(toks, i)
            if t.ty == "ident" {
                cols = push(cols, t.value)
                i = i + 1
                if is_punct(toks, i, ",") {
                    i = i + 1
                } else {
                    cont = false
                }
            } else {
                cont = false
            }
        }
        if is_punct(toks, i, ")") {
            i = i + 1
        }
    }
    if !is_kw(toks, i, "values") {
        return {ty: "error", message: "expected VALUES"}
    }
    i = i + 1
    let rows = []
    let cont = true
    while cont {
        if !is_punct(toks, i, "(") {
            cont = false
        } else {
            i = i + 1
            let row = []
            let inner = true
            while inner {
                let t = tok_at(toks, i)
                if t.ty == "number" || t.ty == "string" || t.ty == "ident" {
                    row = push(row, lit_value(t))
                    i = i + 1
                } else {
                    inner = false
                }
                if is_punct(toks, i, ",") {
                    i = i + 1
                } else {
                    inner = false
                }
            }
            if is_punct(toks, i, ")") {
                i = i + 1
            }
            rows = push(rows, row)
            if is_punct(toks, i, ",") {
                i = i + 1
            } else {
                cont = false
            }
        }
    }
    return {ty: "insert", table: table, columns: cols, rows: rows}
}

fn parse_create(toks) {
    let i = 1
    if !is_kw(toks, i, "table") {
        return {ty: "error", message: "expected TABLE"}
    }
    i = i + 1
    let table = tok_at(toks, i).value
    i = i + 1
    let cols = []
    if is_punct(toks, i, "(") {
        i = i + 1
        let cont = true
        while cont {
            let t = tok_at(toks, i)
            if t.ty == "ident" {
                let name = t.value
                i = i + 1
                let ty_t = tok_at(toks, i)
                let type_name = ""
                if ty_t.ty == "kw" || ty_t.ty == "ident" {
                    type_name = ty_t.value
                    i = i + 1
                }
                cols = push(cols, {name: name, ty: type_name})
                if is_punct(toks, i, ",") {
                    i = i + 1
                } else {
                    cont = false
                }
            } else {
                cont = false
            }
        }
        if is_punct(toks, i, ")") {
            i = i + 1
        }
    }
    return {ty: "create", table: table, columns: cols}
}

fn parse_delete(toks) {
    let i = 1
    if !is_kw(toks, i, "from") {
        return {ty: "error", message: "expected FROM"}
    }
    i = i + 1
    let from = tok_at(toks, i).value
    i = i + 1
    let where = nil
    if is_kw(toks, i, "where") {
        i = i + 1
        let res = parse_where(toks, i)
        where = res.expr
        i = res.pos
    }
    return {ty: "delete", from: from, where: where}
}

fn parse_update(toks) {
    let i = 1
    let table = tok_at(toks, i).value
    i = i + 1
    if !is_kw(toks, i, "set") {
        return {ty: "error", message: "expected SET"}
    }
    i = i + 1
    let sets = []
    let cont = true
    while cont {
        let col = tok_at(toks, i).value
        i = i + 1
        if !is_op(toks, i, "=") {
            cont = false
        } else {
            i = i + 1
            let t = tok_at(toks, i)
            sets = push(sets, {col: col, value: lit_value(t)})
            i = i + 1
            if is_punct(toks, i, ",") {
                i = i + 1
            } else {
                cont = false
            }
        }
    }
    let where = nil
    if is_kw(toks, i, "where") {
        i = i + 1
        let res = parse_where(toks, i)
        where = res.expr
        i = res.pos
    }
    return {ty: "update", table: table, sets: sets, where: where}
}

fn parse_drop(toks) {
    let i = 1
    if !is_kw(toks, i, "table") {
        return {ty: "error", message: "expected TABLE"}
    }
    i = i + 1
    let table = tok_at(toks, i).value
    return {ty: "drop", table: table}
}

fn sql_parse(toks) {
    if len(toks) == 0 {
        return {ty: "error", message: "empty query"}
    }
    let t = toks[0]
    if t.ty != "kw" {
        return {ty: "error", message: "expected keyword"}
    }
    if t.value == "select" {
        return parse_select(toks)
    }
    if t.value == "insert" {
        return parse_insert(toks)
    }
    if t.value == "create" {
        return parse_create(toks)
    }
    if t.value == "delete" {
        return parse_delete(toks)
    }
    if t.value == "update" {
        return parse_update(toks)
    }
    if t.value == "drop" {
        return parse_drop(toks)
    }
    return {ty: "error", message: f"unknown statement: {t.value}"}
}

fn lit_to_str(v) {
    if v == nil {
        return "NULL"
    }
    if v.kind == "null" {
        return "NULL"
    }
    return v.value
}

fn cmp_kind(v) {
    if v == nil {
        return "null"
    }
    return v.kind
}

fn eval_where(expr, row) {
    let op = expr.op
    if op == "and" {
        return eval_where(expr.left, row) && eval_where(expr.right, row)
    }
    if op == "or" {
        return eval_where(expr.left, row) || eval_where(expr.right, row)
    }
    if op == "true" {
        return true
    }
    let col_val = row[expr.col]
    let cmp_val = expr.value
    if col_val == nil {
        return false
    }
    let a = lit_to_str(col_val)
    let b = lit_to_str(cmp_val)
    if cmp_kind(col_val) == "num" && cmp_kind(cmp_val) == "num" {
        let an = int(a)
        let bn = int(b)
        if op == "=" {
            return an == bn
        }
        if op == "!=" || op == "<>" {
            return an != bn
        }
        if op == "<" {
            return an < bn
        }
        if op == ">" {
            return an > bn
        }
        if op == "<=" {
            return an <= bn
        }
        if op == ">=" {
            return an >= bn
        }
    }
    if op == "=" {
        return a == b
    }
    if op == "!=" || op == "<>" {
        return a != b
    }
    if op == "<" {
        return a < b
    }
    if op == ">" {
        return a > b
    }
    if op == "<=" {
        return a <= b
    }
    if op == ">=" {
        return a >= b
    }
    return false
}

fn esc(v) {
    let kind = v.kind
    if kind == "null" {
        return "\n"
    }
    let s = v.value
    let out = ""
    for ch in s {
        if ch == " " {
            out = out + "\s"
        } else if ch == "\" {
            out = out + "\\"
        } else if ch == "
" {
            out = out + "\l"
        } else {
            out = out + ch
        }
    }
    if kind == "num" {
        return "N" + out
    }
    return "S" + out
}

fn unesc(p) {
    if p == "\n" {
        return {kind: "null", value: ""}
    }
    let kind = substr(p, 0, 1)
    let body = substr(p, 1, len(p) - 1)
    let out = ""
    let i = 0
    while i < len(body) {
        let c = body[i]
        if c == "\" && i + 1 < len(body) {
            let nx = body[i + 1]
            if nx == "s" {
                out = out + " "
            } else if nx == "\" {
                out = out + "\"
            } else if nx == "l" {
                out = out + "
"
            } else {
                out = out + nx
            }
            i = i + 2
        } else {
            out = out + c
            i = i + 1
        }
    }
    if kind == "N" {
        return {kind: "num", value: out}
    }
    return {kind: "str", value: out}
}

fn db_serialize(db) {
    let out = ""
    let tnames = keys(db.tables)
    for name in tnames {
        let table = db.tables[name]
        if table != nil {
            out = out + "T " + name + "
"
            out = out + "C"
            for c in table.columns {
                out = out + " " + c.name + ":" + c.ty
            }
            out = out + "
"
            for row in table.rows {
                out = out + "R"
                for v in row {
                    out = out + " " + esc(v)
                }
                out = out + "
"
            }
        }
    }
    return out
}

fn db_deserialize(s) {
    let db = {tables: {}, file: ""}
    let lines = split(s, "
")
    let cur_name = ""
    let cur_table = nil
    for line in lines {
        if len(line) >= 2 && substr(line, 0, 2) == "T " {
            cur_name = substr(line, 2, len(line) - 2)
            cur_table = {columns: [], rows: []}
        } else if len(line) >= 1 && substr(line, 0, 1) == "C" {
            let parts = split(substr(line, 2, len(line) - 2), " ")
            let cols = []
            for p in parts {
                if p != "" {
                    let kv = split(p, ":")
                    cols = push(cols, {name: kv[0], ty: kv[1]})
                }
            }
            cur_table.columns = cols
        } else if len(line) >= 1 && substr(line, 0, 1) == "R" {
            let parts = split(substr(line, 2, len(line) - 2), " ")
            let row = []
            for p in parts {
                if p != "" {
                    row = push(row, unesc(p))
                }
            }
            cur_table.rows = push(cur_table.rows, row)
            db.tables[cur_name] = cur_table
        }
    }
    return db
}

fn db_save() {
    if g_db.file != "" {
        file_write(g_db.file, db_serialize(g_db))
    }
}

fn db_load(path) {
    if file_exists(path) {
        let s = file_read(path)
        let db = db_deserialize(s)
        db.file = path
        return db
    }
    let d = {tables: {}, file: path}
    return d
}

fn sql_exec(db, q) {
    if q.ty == "error" {
        return {ok: false, message: q.message, rows: []}
    }
    if q.ty == "create" {
        g_db.tables[q.table] = {columns: q.columns, rows: []}
        db_save()
        return {ok: true, message: f"created table {q.table}", rows: []}
    }
    if q.ty == "insert" {
        let table = g_db.tables[q.table]
        if table == nil {
            return {ok: false, message: f"no such table {q.table}", rows: []}
        }
        for row in q.rows {
            let full = []
            for c in table.columns {
                let found = false
                let idx = 0
                while idx < len(q.columns) {
                    if q.columns[idx] == c.name {
                        found = true
                    }
                    idx = idx + 1
                }
                if found {
                    let j = 0
                    while j < len(q.columns) {
                        if q.columns[j] == c.name {
                            full = push(full, row[j])
                        }
                        j = j + 1
                    }
                } else {
                    full = push(full, {kind: "null", value: ""})
                }
            }
            table.rows = push(table.rows, full)
        }
        g_db.tables[q.table] = table
        db_save()
        return {ok: true, message: "inserted", rows: []}
    }
    if q.ty == "select" {
        let table = g_db.tables[q.from]
        if table == nil {
            return {ok: false, message: f"no such table {q.from}", rows: []}
        }
        let out_rows = []
        let cols = []
        if len(q.columns) == 1 && q.columns[0] == "*" {
            for c in table.columns {
                cols = push(cols, c.name)
            }
        } else {
            cols = q.columns
        }
        out_rows = push(out_rows, cols)
        for row in table.rows {
            let row_map = {}
            let idx = 0
            while idx < len(table.columns) {
                row_map[table.columns[idx].name] = row[idx]
                idx = idx + 1
            }
            let ok = true
            if q.where != nil {
                ok = eval_where(q.where, row_map)
            }
            if ok {
                let out = []
                for c in cols {
                    out = push(out, lit_to_str(row_map[c]))
                }
                out_rows = push(out_rows, out)
            }
        }
        return {ok: true, message: "ok", rows: out_rows}
    }
    if q.ty == "delete" {
        let table = g_db.tables[q.from]
        if table == nil {
            return {ok: false, message: f"no such table {q.from}", rows: []}
        }
        let kept = []
        let removed = 0
        for row in table.rows {
            let row_map = {}
            let idx = 0
            while idx < len(table.columns) {
                row_map[table.columns[idx].name] = row[idx]
                idx = idx + 1
            }
            let del = false
            if q.where != nil {
                del = eval_where(q.where, row_map)
            }
            if del {
                removed = removed + 1
            } else {
                kept = push(kept, row)
            }
        }
        table.rows = kept
        g_db.tables[q.from] = table
        db_save()
        return {ok: true, message: f"deleted {removed} rows", rows: []}
    }
    if q.ty == "update" {
        let table = g_db.tables[q.table]
        if table == nil {
            return {ok: false, message: f"no such table {q.table}", rows: []}
        }
        let updated = 0
        let new_rows = []
        for row in table.rows {
            let row_map = {}
            let idx = 0
            while idx < len(table.columns) {
                row_map[table.columns[idx].name] = row[idx]
                idx = idx + 1
            }
            let matches = true
            if q.where != nil {
                matches = eval_where(q.where, row_map)
            }
            if matches {
                let nr = []
                let j = 0
                while j < len(table.columns) {
                    let setv = row[j]
                    for s in q.sets {
                        if table.columns[j].name == s.col {
                            setv = s.value
                        }
                    }
                    nr = push(nr, setv)
                    j = j + 1
                }
                new_rows = push(new_rows, nr)
                updated = updated + 1
            } else {
                new_rows = push(new_rows, row)
            }
        }
        table.rows = new_rows
        g_db.tables[q.table] = table
        db_save()
        return {ok: true, message: f"updated {updated} rows", rows: []}
    }
    if q.ty == "drop" {
        g_db.tables[q.table] = nil
        db_save()
        return {ok: true, message: f"dropped {q.table}", rows: []}
    }
    return {ok: false, message: "unknown query", rows: []}
}

fn json_escape(s) {
    let out = ""
    for ch in s {
        if ch == """ {
            out = out + "\""
        } else if ch == "\" {
            out = out + "\\"
        } else if ch == "
" {
            out = out + "\n"
        } else {
            out = out + ch
        }
    }
    return out
}

fn json_cell(cell) {
    if cell == "NULL" {
        return "null"
    }
    let isnum = true
    try {
        let _ = int(cell)
    } catch e {
        isnum = false
    }
    if isnum {
        return cell
    }
    return f""{json_escape(cell)}""
}

fn json_result(result) {
    let out = "{"ok":"
    if result.ok {
        out = out + "true"
    } else {
        out = out + "false"
    }
    out = out + ","message":"" + json_escape(result.message) + "","rows":["
    let first = true
    for row in result.rows {
        if !first {
            out = out + ","
        }
        first = false
        out = out + "["
        let f2 = true
        for cell in row {
            if !f2 {
                out = out + ","
            }
            f2 = false
            out = out + json_cell(cell)
        }
        out = out + "]"
    }
    return out + "]}"
}

fn run_query(sql) {
    let toks = sql_lex(sql)
    let q = sql_parse(toks)
    let r = sql_exec(q)
    return json_result(r)
}

fn handle_client(stream) {
    let line = tcp_read_line(stream)
    if line == "" || line == nil {
        tcp_close(stream)
        return
    }
    if line == "QUIT" {
        tcp_close(stream)
        return
    }
    let resp = ""
    try {
        resp = run_query(line)
    } catch e {
        resp = f"{{"ok":false,"message":"{e}","rows":[]}}"
    }
    tcp_write(stream, resp + "
")
    tcp_close(stream)
}

let g_db = db_load("rakdb.dat")
let listener = net_listen("127.0.0.1:18393")
print("rak-sql listening on 127.0.0.1:18393 (send SQL lines, JSON back)")

let running = true
while running {
    let conn = net_accept(listener)
    let stream = conn.0
    handle_client(stream)
}
]]

return example
