-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- traits.rak: traits
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[traits]]

example.filename = [[traits.rak]]

example.source = [[
// traits.rak -- Display, Iterable, Index, IndexMut.
// The receiver is passed as the first argument of each method.

struct Point { x: int, y: int }

impl Display for Point {
    fn fmt(self) { return fmt("({}, {})", self.x, self.y) }
}
dump Point { x: 3, y: 4 }   // (3, 4)

struct Range { lo: int, hi: int }
impl Iterable for Range {
    fn iter(self) {
        let out = []
        let i = self.lo
        while i <= self.hi { out = push(out, i); i = i + 1 }
        return out
    }
}

let s = 0
for n in Range { lo: 1, hi: 5 } { s = s + n }
dump s   // 15

struct Table { entries: map }
impl Index for Table {
    fn index(self, key) { return get(self.entries, key, 0) }
}
impl IndexMut for Table {
    fn set(self, key, value) { self.entries[key] = value; return self }
}

let t = Table { entries: {a: 1, b: 2} }
dump t["a"]   // 1
t["c"] = 99
dump t["c"]   // 99
]]

return example
