-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- VPN/psk_tunnel.rak: vpn_psk_tunnel
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[vpn_psk_tunnel]]

example.filename = [[VPN/psk_tunnel.rak]]

example.source = [[
// VPN: the 'tunnel' keyword.
// Builds an encrypted UDP conduit and exposes its session key to the block.
// Interpreter only. Run with:  rakc run examples/VPN/psk_tunnel.rak
tunnel link "shared-very-secret-passphrase" {
    dump fmt("session key = 0x{}", hex_encode(link))
    dump "conduit = " + link_addr
    let ack = chacha20_encrypt(link, tunnel_nonce(1), b"rak:tunnel:data", b"tunnel-ack")
    dump fmt("encoded ack = 0x{}", hex_encode(ack))
    let back = chacha20_decrypt(link, tunnel_nonce(1), b"rak:tunnel:data", ack)
    dump "round-trip = " + string(back)
}
]]

return example
