-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- VPN/vpn_over_http.rak: vpn_over_http
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[vpn_over_http]]

example.filename = [[VPN/vpn_over_http.rak]]

example.source = [[
// VPN: covert transport - shuttle encrypted tunnel frames through HTTP.
// A client POSTs an encrypted, framed datagram to /tunnel; the server relay
// decrypts it. Interpreter only. Run with:  rakc run examples/VPN/vpn_over_http.rak
let key = tunnel_preshared_key("http-covert-psk", b"rak-http-salt", 1000, 32)
let port = http_server_start("127.0.0.1", 8199)
dump fmt("covert relay on 127.0.0.1:{}", port)
fn client_post() {
    let inner = chacha20_encrypt(key, tunnel_nonce(1), b"rak:http", b"TOP_SECRET_ROUTED_DATAGRAM")
    fetch "http://127.0.0.1:" + port + "/tunnel" { method: "POST", body: hex_encode(tunnel_frame(1, inner)) } {
        dump fmt("[client] relay status {}", status)
    }
}
spawn(fn() { client_post() })
let relayed = false
let guard = 0
while !relayed {
    let req = http_server_poll()
    if req == nil {
        sleep(10)
    } else {
        if req.path == "/tunnel" {
            let parsed = tunnel_unframe(hex_decode(req.body))
            let clear = chacha20_decrypt(key, tunnel_nonce(1), b"rak:http", parsed.1)
            dump fmt("[server] decrypted: {}", string(clear))
            http_server_respond(req.id, 200, {}, "delivered")
            relayed = true
        } else {
            http_server_respond(req.id, 404, {}, "not found")
        }
    }
    guard = guard + 1
    if guard > 2000 { dump "gave up"; relayed = true }
}
]]

return example
