-- GENERATED by scripts/gen-rak-examples.ts - do not edit by hand.
-- VPN/chacha_tunnel.rak: vpn_chacha_tunnel
--
-- `source` is a Lua long-bracket string, which performs no escape processing,
-- so Rak regexes and backslashes survive verbatim.

local example = {}

example.name = [[vpn_chacha_tunnel]]

example.filename = [[VPN/chacha_tunnel.rak]]

example.source = [[
// VPN: ChaCha20-Poly1305 AEAD + tunnel framing.
// Derive a session key, encrypt+frame a datagram, decrypt it, and prove that
// a tampered header is rejected. Run with:  rakc run examples/VPN/chacha_tunnel.rak
let key = tunnel_preshared_key("correct horse battery staple", b"salt", 10000, 32)
let nonce = tunnel_nonce(0)
let aad = b"rak:v1:seq0"
let ct = chacha20_encrypt(key, nonce, aad, b"HELLO_VPN")
let frame = tunnel_frame(0, ct)
let parsed = tunnel_unframe(frame)
let recovered = chacha20_decrypt(key, nonce, aad, parsed.1)
dump fmt("decrypted: {}", string(recovered))
try {
    chacha20_decrypt(key, nonce, b"rak:v1:seq9", ct)
    dump "tampered ACCEPTED (BAD!)"
} catch e {
    dump fmt("tampered rejected: {}", e)
}
]]

return example
