-- Rak Examples — starter scripts as Command Palette entries.
--
-- These used to live in a hard-coded `Examples` dropdown in the editor toolbar,
-- which meant the Rak-specific content was permanent IDE chrome: visible whether
-- or not the user wanted Rak, and impossible to extend or remove. As a
-- contribution, the whole feature disappears when this extension is not
-- installed.
--
-- Each example becomes its own command, so the Command Palette lists them all
-- under one searchable prefix and `fuzzy`-filtering by name works the way a
-- user expects.

-- Extension Activation Entry Point
function activate(context)
    -- One module per example under `src/examples/`, generated by
    -- `scripts/gen-rak-examples.ts` from the old bundled table.
    local examples = require("src.examples")

    for _, example in ipairs(examples) do
        -- The palette title is the human label; the command id is namespaced by
        -- the extension so two extensions can both offer an `example.hello`.
        local title = string.format("Rak: Example — %s", example.name)

        agamiz.commands.register("rak-examples.open." .. example.filename, {
            title = title,
        }, function()
            -- `open_buffer` creates a *new* untitled tab. That is the whole
            -- reason this extension is possible: the other `agamiz.editor.*`
            -- entry points can only rewrite the buffer that is already open, so
            -- an extension had no way to show the user anything new.
            --
            -- The buffer has no path on disk, so Ctrl+S prompts for a location
            -- rather than silently overwriting anything.
            agamiz.editor.open_buffer(example.filename, example.source)
            agamiz.window.show_message("info", string.format(
                "Opened %s in a new tab. Save it to run it, or press Ctrl+R.",
                example.filename))
        end)
    end

    agamiz.log(string.format("rak-examples activated with %d examples", #examples))
end

-- Extension Deactivation Cleanup
function deactivate()
    -- Every command above is a Lua closure owned by this VM, so discarding the
    -- VM removes them from the palette. Nothing else to release.
    agamiz.log("rak-examples deactivated")
end
